typography_spectrum: 0.03008133894763887
color:
  brandStrength: 0.2741815021727234
  lightness: 0.2919766448903829
  saturation: 0.1443449028301984
  rhythmicContrast: 0.4022607277147472
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.0748804328031838
author:
  name: Steve Balan
  email: Mail@Steve-Balan.com
  url: www.Steve-Balan.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd19254a-36db-434c-af7d-a8fae6e64d80.png
name: Steve Balan Blog
